import type { AnimationTheme } from "../types/pipeline.types.js";

export const ANIMATION_THEMES: AnimationTheme[] = [
  {
    id: "studio",
    name: "Studio",
    description: "Professional dark theme with neutral tones and clean contrast.",
    background: "#0F0F0F",
    surface: "#1A1A1A",
    raised: "#262626",
    textPrimary: "#FAFAFA",
    textMuted: "#A3A3A3",
    accents: {
      hookFear: "#EF4444",
      wrongPath: "#F59E0B",
      techCode: "#06B6D4",
      revelation: "#22C55E",
      cta: "#EAB308",
      violet: "#8B5CF6",
    },
  },
  {
    id: "studio-violet",
    name: "Studio Violet",
    description: "Dark theme with violet and purple tones as the dominant accent.",
    background: "#0D0B14",
    surface: "#1A1625",
    raised: "#271F38",
    textPrimary: "#F5F0FF",
    textMuted: "#A78BCC",
    accents: {
      hookFear: "#F43F5E",
      wrongPath: "#D97706",
      techCode: "#A78BFA",
      revelation: "#34D399",
      cta: "#FBBF24",
      violet: "#C084FC",
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "Vibrant, high-contrast dark theme with bright neon accent colors.",
    background: "#050505",
    surface: "#0A0A0A",
    raised: "#141414",
    textPrimary: "#FFFFFF",
    textMuted: "#8B8B8B",
    accents: {
      hookFear: "#FF2D55",
      wrongPath: "#FF9500",
      techCode: "#00D4FF",
      revelation: "#30FF85",
      cta: "#FFE600",
      violet: "#BF5AF2",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Cool blue-toned theme with deep navy backgrounds and aqua accents.",
    background: "#0A1628",
    surface: "#0F2035",
    raised: "#162D4A",
    textPrimary: "#E8F4FD",
    textMuted: "#7BA7C9",
    accents: {
      hookFear: "#F87171",
      wrongPath: "#FBBF24",
      techCode: "#22D3EE",
      revelation: "#2DD4BF",
      cta: "#FDE68A",
      violet: "#818CF8",
    },
  },
  {
    id: "daylight",
    name: "Daylight",
    description: "Light, bright theme with warm backgrounds and vivid accent colors.",
    background: "#FFFBF5",
    surface: "#FFFFFF",
    raised: "#F5F0E8",
    textPrimary: "#1C1917",
    textMuted: "#78716C",
    accents: {
      hookFear: "#DC2626",
      wrongPath: "#D97706",
      techCode: "#0891B2",
      revelation: "#16A34A",
      cta: "#CA8A04",
      violet: "#7C3AED",
    },
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    description: "Minimal, muted theme with subtle colors and clean typography focus.",
    background: "#F8F8F8",
    surface: "#FFFFFF",
    raised: "#F0F0F0",
    textPrimary: "#2D2D2D",
    textMuted: "#9CA3AF",
    accents: {
      hookFear: "#E57373",
      wrongPath: "#FFB74D",
      techCode: "#4FC3F7",
      revelation: "#81C784",
      cta: "#FFD54F",
      violet: "#B39DDB",
    },
  },
];

export const DEFAULT_THEME_ID = "studio";
