import type { AnimationTheme } from "../types/pipeline.types.js";

export const ANIMATION_THEMES: AnimationTheme[] = [
  {
    id: "studio",
    name: "Studio",
    description: "Professional dark theme with neutral tones and clean contrast.",
    background: "#0A0A0F",
    surface: "#14141F",
    raised: "#1E1E2E",
    textPrimary: "#F0F0F5",
    textMuted: "#8888A0",
    accents: {
      hookFear: "#EF4444",
      wrongPath: "#F59E0B",
      techCode: "#06B6D4",
      revelation: "#22C55E",
      cta: "#EAB308",
      violet: "#8B5CF6",
    },
  },
  {
    id: "studio-violet",
    name: "Studio Violet",
    description: "Deep violet theme with purple-dominant glow and rich accent palette.",
    background: "#0B0815",
    surface: "#151025",
    raised: "#201838",
    textPrimary: "#F0EAFF",
    textMuted: "#9880BB",
    accents: {
      hookFear: "#F43F5E",
      wrongPath: "#D97706",
      techCode: "#A78BFA",
      revelation: "#34D399",
      cta: "#FBBF24",
      violet: "#C084FC",
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "High-energy neon theme with vivid electric accents and deep black canvas.",
    background: "#050508",
    surface: "#0A0A12",
    raised: "#12121E",
    textPrimary: "#FFFFFF",
    textMuted: "#7A7A95",
    accents: {
      hookFear: "#FF2D55",
      wrongPath: "#FF9500",
      techCode: "#00D4FF",
      revelation: "#30FF85",
      cta: "#FFE600",
      violet: "#BF5AF2",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep sea theme with navy canvas and cool aqua/teal glow accents.",
    background: "#060E1C",
    surface: "#0C1828",
    raised: "#122438",
    textPrimary: "#E0F0FF",
    textMuted: "#6090B8",
    accents: {
      hookFear: "#F87171",
      wrongPath: "#FBBF24",
      techCode: "#22D3EE",
      revelation: "#2DD4BF",
      cta: "#FDE68A",
      violet: "#818CF8",
    },
  },
  {
    id: "ember",
    name: "Ember",
    description: "Warm dark theme with amber and orange glow, fiery accent palette.",
    background: "#0C0806",
    surface: "#161010",
    raised: "#221818",
    textPrimary: "#FFF0E8",
    textMuted: "#A08070",
    accents: {
      hookFear: "#EF4444",
      wrongPath: "#F97316",
      techCode: "#FB923C",
      revelation: "#34D399",
      cta: "#FBBF24",
      violet: "#E879F9",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Ultra-dark theme with cool blue undertones and crisp white text.",
    background: "#06060C",
    surface: "#0C0C18",
    raised: "#141428",
    textPrimary: "#F5F5FF",
    textMuted: "#7070A0",
    accents: {
      hookFear: "#FF6B6B",
      wrongPath: "#FFD93D",
      techCode: "#6BCB77",
      revelation: "#4D96FF",
      cta: "#FFD93D",
      violet: "#9B59B6",
    },
  },
];

export const DEFAULT_THEME_ID = "neon";
